from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_DATA_YAML = Path(r"/home/martin/ML/Image/CardSeg/video_card_hand_project_yolo_dataset/dataset.yaml")
DEFAULT_PROJECT_DIR = Path(__file__).resolve().parent / "runs"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a YOLO segmentation model for card and hand foreground extraction.",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="yoloe-26s-seg.pt",
        help="Model name, local weight path, or model yaml accepted by ultralytics.YOLO.",
    )
    parser.add_argument(
        "--data",
        type=str,
        default=str(DEFAULT_DATA_YAML),
        help="Path to the dataset.yaml generated by data_process.py. Override this on the Linux server.",
    )
    parser.add_argument("--epochs", type=int, default=120, help="Training epochs.")
    parser.add_argument("--imgsz", type=int, default=1024, help="Square training image size.")
    parser.add_argument(
        "--batch",
        type=int,
        default=8,
        help="Batch size. Increase on the GPU server if memory allows.",
    )
    parser.add_argument("--device", type=str, default="2", help='CUDA device id, for example "0" or "0,1".')
    parser.add_argument("--workers", type=int, default=8, help="Data loader workers.")
    parser.add_argument("--project", type=str, default=str(DEFAULT_PROJECT_DIR), help="Ultralytics run root.")
    parser.add_argument("--name", type=str, default="card_hand_yoloe26s_seg", help="Run name.")
    parser.add_argument("--patience", type=int, default=30, help="Early stop patience.")
    parser.add_argument("--resume", action="store_true", help="Resume the latest interrupted run.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    try:
        from ultralytics import YOLO
    except ImportError as exc:
        raise ImportError(
            "ultralytics is required. Install it on the GPU server with `pip install ultralytics`."
        ) from exc

    data_path = Path(args.data)
    if not data_path.exists():
        raise FileNotFoundError(f"Dataset yaml does not exist: {data_path}")

    project_dir = Path(args.project)
    project_dir.mkdir(parents=True, exist_ok=True)

    train_kwargs = {
        "data": str(data_path),
        "epochs": args.epochs,
        "imgsz": args.imgsz,
        "batch": args.batch,
        "device": args.device,
        "workers": args.workers,
        "project": str(project_dir),
        "name": args.name,
        "patience": args.patience,
        "task": "segment",
        "optimizer": "AdamW",
        "lr0": 0.08,
        "cos_lr": True,
        "warmup_epochs": 3.0,
        "close_mosaic": 10,
        "degrees": 3.0,
        "translate": 0.05,
        "scale": 0.20,
        "shear": 1.0,
        "perspective": 0.0005,
        "fliplr": 0.5,
        "flipud": 0.5,
        "hsv_h": 0.012,
        "hsv_s": 0.35,
        "hsv_v": 0.20,
        "mosaic": 0.5,
        "mixup": 0.1,
        "copy_paste": 0.3,
        "erasing": 0.1,
        "cache": False,
        "multi_scale": True,
        "amp": True,
        "pretrained": True,
        "plots": True,
        "save": True,
        "save_period": 10,
        "val": True,
        "verbose": True
    }

    if args.resume:
        train_kwargs["resume"] = True

    print("Training configuration")
    for key in (
        "data",
        "epochs",
        "imgsz",
        "batch",
        "device",
        "optimizer",
        "degrees",
        "translate",
        "scale",
        "perspective",
        "fliplr",
        "hsv_h",
        "hsv_s",
        "hsv_v",
        "mosaic",
        "mixup",
        "copy_paste",
    ):
        print(f"  {key}: {train_kwargs[key]}")

    model = YOLO(args.model)
    results = model.train(**train_kwargs)

    print("Training finished")
    print(f"Run directory: {results.save_dir}")
    print(f"Best weights: {Path(results.save_dir) / 'weights' / 'best.pt'}")


if __name__ == "__main__":
    main()
